# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uy3MDnTF1rKl6n8BySBE-9KxvfqienqA
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import accuracy_score

# import data

# split features & target 
# x
# y

# split train data & test data

# function to perform training with Entropy
classification = DecisionTreeClassifier(criterion='entropy', random_state=100, max_depth=3, min_samples_leaf=5)
classification.fit(x_train,y_train)

# Prediction

# accuracy

