# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18wxhkOsZspFjjavV_3nah_i440P6SV8a
"""

# Step1: Import required packages
from pandas import pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

# load data
iris_data = pd.read_csv('iris.csv')
# check missing values
# categorical data

# split target & features

# split training & test data

# model using Support Vector Machine 
# kernel='linear' or 'polynomial' or 'radial basis function'
classifier = SVC()
classifier.fit(x_train,y_train)

# Prediction
# Accuracy